---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: edge
spec:
  releaseName: external-dns
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.5.1
  valuesFrom:
  - configMapKeyRef:
      name: external-dns-helm-values
      key: values.yaml  
  values:
    aws:
      region: eu-central-1
      zoneType: public
    fullnameOverride: external-dns
    logLevel: info
    policy: sync
    rbac:
      create: true
    resources:
      limits:
        cpu: 50m
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 50Mi
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: external-dns
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-dns