---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: edge
spec:
  forceUpgrade: true
  rollback:
    recreate: true
  releaseName: nginx-ingress
  helmVersion: v3
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.8.0
  values:
    controller:
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
    tcp:
      22: "gitea/gitea-ssh:22"
