---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: edge
spec:
  forceUpgrade: true
  rollback:
    recreate: true
  releaseName: nginx-ingress
  helmVersion: v3
  chart:
    repository: https://helm.nginx.com/stable
    name: nginx-ingress
    version: 0.7.0
  values:
    tcp:
      22: "gitlab-server/gitlab-gitlab-shell:22"
