---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: edge
spec:
  forceUpgrade: true
  rollback:
    recreate: true
  releaseName: nginx-ingress
  helmVersion: v3
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: nginx-ingress
    version: 3.8.0